### ISSUE TITLE
Pas sur de comprendre

### ISSUE THREAD

**Issue by MRossignol** [mathieulagrange/paperSpeedSoundFinding2016#2]
Soit ce paragraphe redit plusieurs fois quasiment la même chose (et dans ce cas il faut "dégraisser"), soit je ne comprends rien (et c'est mauvais signe !). Ligne 192 :

More precisely, with the FSD display, users can directly visualize the whole hierarchy, down to the leaf classes, while with the PSD display, users only have access, at first, to the intermediate semantic levels of the hierarchy. Upon first using PSD, they observe circles representing the top classes of the semantic hierarchical structure of the dataset. When users click on a circle, they hear the sound prototype of the class and the subclasses are progressively revealed, represented by white circles contained in the circle that has just been clicked. The same action repeats itself until the user reaches the leaf classes of the hierarchy. The leaf classes are represented with small gray circles, indicating that there is no subclass to uncover. Thus the PSD has a constrained exploration system. When a user clicks on a circle, sub-circles are  automatically revealed to him in a gradual way. Each time a sub-circle is automatically revealed, its sound prototype is played. Users may stop the discovery process by clicking on an other circle. In this display, the leaf classes are distributed  in the same manner as FSD. Thus, the spatial configuration of the unfolded version of PSD, which may be obtained after discovering all the classes and subclasses, is equivalent to the one of FSD, as shown on Figures~\ref{figXP2}, \ref{figXP1} and \ref{figSSF}.

**Comment by mathieulagrange** [comment]
enlever un peu, mais bon, vaut mieux etre redondant !!
